# Specifies a parent image
FROM golang:1.18

# Create the app directory to hold app’s source code

ADD ./waku-subscribe /go/bin/waku-subscribe
RUN umask -S 202
RUN mkdir -p /go/bin/out

ADD ./subscribe.go /go/src/subscribe.go
ADD go.mod go.sum /go/src/

# Tells Docker which network port your container listens on
EXPOSE 8080

# Specifies the executable command that runs when the container starts
ENTRYPOINT [ "/go/bin/waku-subscribe"]
